# Generated by Django 4.1 on 2022-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, upload_to='image_directory_path'),
        ),
        migrations.DeleteModel(
            name='Footprint',
        ),
    ]
